kind: Deployment
metadata:
  name: joao-marcos-front-recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joao-marcos-front-recommendation
  template:
    metadata:
      labels:
        app: joao-marcos-front-recommendation
    spec:
      containers:
        - env:
          - name: API_URL
            value: http://10.10.10.10:32188
        - name: joao-marcos-front-recommendation
          image:  joaovitorsd/tp-cloud-comp-front:latest
          ports:
          - containerPort: 3000