apiVersion: apps/v1
kind: Deployment
metadata:
  name: joao-marcos-front-recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joao-marcos-front-recommendation
  template:
    metadata:
      labels:
        app: joao-marcos-front-recommendation
    spec:
      containers:
        - name: joao-marcos-front-recommendation
          image:  joaovitorsd/tp-cloud-comp-front:latest
          env:
           - name: API_URL
             value: http://joao-marcos-api-recommendation-service:32188
          ports:
           - containerPort: 3000