apiVersion: v1
kind: Service
metadata:
  name: joao-marcos-front-recommendation-service
spec:
  type: LoadBalancer
  selector:
    app: joao-marcos-front-recommendation
  ports:
    - protocol: TCP
      port: 32202
      targetPort: 3000
      nodePort: 32202
